=== CoRE-RG/SignalsAndGateways/src/gateway/GatewayConfig.dtd
<!ELEMENT config				((gateway)+)>

<!ELEMENT gateway				((routing)?, (buffering)?, (transformation)*)>
<!ATTLIST gateway
	id			CDATA	#REQUIRED
>

<!ELEMENT routing				((route)+)>
<!ELEMENT route					((canframe)+ | (ethernetframe)+ | (ctframe)+ | (ttframe)+)>
<!ATTLIST route
	source		CDATA	#REQUIRED
	destination CDATA	#REQUIRED
>
<!ELEMENT canframe		EMPTY>
<!ATTLIST canframe
	canId		CDATA	#REQUIRED
>
<!ELEMENT ethernetframe	((canframe)*)>
<!ATTLIST ethernetframe
	dst			CDATA	#REQUIRED
>
<!ELEMENT rcframe		((canframe)*)>
<!ATTLIST rcframe
	ctId		CDATA	#REQUIRED
>
<!ELEMENT ttframe		((canframe)*)>
<!ATTLIST ttframe
	ctId		CDATA	#REQUIRED
>

<!ELEMENT buffering				((pool)+)>
<!ELEMENT pool					((holdup)+)>
<!ELEMENT holdup				((canframe)+)>
<!ATTLIST holdup
	time		CDATA	#REQUIRED
>
<!ELEMENT canframe		EMPTY>
<!ATTLIST canframe
	canId		CDATA	#REQUIRED
>

<!ELEMENT transformation		((canframe)+ | (ethernetframe)+ | (ctframe)+ | (ttframe)+)>
<!ATTLIST transformation
	destination	CDATA				#REQUIRED
	type		(toEthernet|toCan)	#REQUIRED
>

=== CoRE-RG/SignalsAndGateways/examples/smallNetwork/GatewayConfig_withQ.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE config SYSTEM "../../src/signalsandgateways/gateway/GatewayConfig.dtd">-->
<config>

	<gateway id="gateway1">
		<routing>
			<route source="0" destination="1">
				<canframe canId="1"/>
				<canframe canId="2"/>
				<canframe canId="3"/>
			</route>
		</routing>
		<buffering>
			<pool>
				<holdup time="5ms">
					<canframe canId="1"/>
				</holdup>
				<holdup time="10ms">
					<canframe canId="2"/>
				</holdup>
			</pool>
		</buffering>
		<transformation destination="1" type="toEthernet">
			<ethernetqframe dst="0A-00-00-00-00-04" vid="1" pcp="7">
				<canframe canId="1"/>
				<canframe canId="2"/>
				<canframe canId="3"/>
			</ethernetqframe>
		</transformation>
	</gateway>
	
	<gateway id="gateway2">
		<routing>
			<route source="1" destination="0">
				<ethernetqframe dst="0A-00-00-00-00-04" vid="1"/>
			</route>
		</routing>
		<transformation destination="0" type="toCan">
			<ethernetqframe dst="0A-00-00-00-00-04"/>
		</transformation>
	</gateway>
	
</config>

=== CoRE-RG/SignalsAndGateways/examples/smallNetwork/GatewayConfig_withCT.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE config SYSTEM "../../src/signalsandgateways/gateway/GatewayConfig.dtd">-->
<config>

	<gateway id="gateway1">
		<routing>
			<route source="0" destination="1">
				<canframe canId="1"/>
				<canframe canId="2"/>
				<canframe canId="3"/>
			</route>
		</routing>
		<buffering>
			<pool>
				<holdup time="5ms">
					<canframe canId="1"/>
				</holdup>
				<holdup time="10ms">
					<canframe canId="2"/>
				</holdup>
			</pool>
		</buffering>
		<transformation destination="1" type="toEthernet">
			<ttframe ctId="1">
				<canframe canId="1"/>
				<canframe canId="2"/>
				<canframe canId="3"/>
			</ttframe>
		</transformation>
	</gateway>
	
	<gateway id="gateway2">
		<routing>
			<route source="1" destination="0">
				<ttframe ctId="1"/>
			</route>
		</routing>
		<transformation destination="0" type="toCan">
			<ttframe ctId="1"/>
		</transformation>
	</gateway>
	
</config>
