=== CoRE-RG/SignalsAndGateways/src/gateway/routing/RoutingTable.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT routingTable				((item)*)>
<!ATTLIST routingTable
	DTDversion		CDATA #REQUIRED
>
<!-- DTD version: 1.1 -->

<!ELEMENT item						((source), (destination)+, (options)*)>

<!ELEMENT source (sourceBusID, sourceObjectID, sourceType)>
<!ELEMENT sourceBusID				(#PCDATA)>
<!ELEMENT sourceObjectID			(#PCDATA)>
<!ELEMENT sourceType				(#PCDATA)>

<!ELEMENT destination (destinationBusID, destinationObjectID, destinationType, backboneCTID, backboneTransferType)>
<!ELEMENT destinationBusID			(#PCDATA)>
<!ELEMENT destinationObjectID		(#PCDATA)>
<!ELEMENT destinationType			(#PCDATA)>
<!ELEMENT backboneCTID				(#PCDATA)>
<!ELEMENT backboneTransferType		(#PCDATA)>

<!ELEMENT options ((holdUpTime)*)>
<!ELEMENT holdUpTime				(#PCDATA)>

=== CoRE-RG/SignalsAndGateways/examples/RoutingTable.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE routingTable SYSTEM "../src/gateway/routing/RoutingTable.dtd">

<routingTable>
	<item>
		<source>
			<sourceBusID>
				canbus1
			</sourceBusID>
			<sourceObjectID>
				1
			</sourceObjectID>
			<sourceType>
				can
			</sourceType>
			<sourceChannel>
				
			</sourceChannel>
		</source>
		<destination>
			<destinationBusID>
				canbus2
			</destinationBusID>
			<destinationObjectID>
				1
			</destinationObjectID>
			<destinationType>
				can
			</destinationType>
			<destinationChannel>
				
			</destinationChannel>
			<backboneCTID>
				100
			</backboneCTID>
		</destination>
		<options>
			<holdUpTime>
			
			</holdUpTime>
		</options>
	</item>
	
	<item>
		<source>
			<sourceBusID>
				canbus1
			</sourceBusID>
			<sourceObjectID>
				5
			</sourceObjectID>
			<sourceType>
				van
			</sourceType>
			<sourceChannel>
				
			</sourceChannel>
		</source>
		<destination>
			<destinationBusID>
				canbus2
			</destinationBusID>
			<destinationObjectID>
				5
			</destinationObjectID>
			<destinationType>
				can
			</destinationType>
			<destinationChannel>
				
			</destinationChannel>
			<backboneCTID>
				10
			</backboneCTID>
		</destination>
		<options>
			<holdUpTime>
			
			</holdUpTime>
		</options>
	</item>
	
	<item>
		<source>
			<sourceBusID>
				canbus2
			</sourceBusID>
			<sourceObjectID>
				2
			</sourceObjectID>
			<sourceType>
				can
			</sourceType>
			<sourceChannel>
				
			</sourceChannel>
		</source>
		<destination>
			<destinationBusID>
				canbus2
			</destinationBusID>
			<destinationObjectID>
				2
			</destinationObjectID>
			<destinationType>
				can
			</destinationType>
			<destinationChannel>
				
			</destinationChannel>
			<backboneCTID>
				150
			</backboneCTID>
		</destination>
		<options>
			<holdUpTime>
			
			</holdUpTime>
		</options>
	</item>
	
	<item>
		<source>
			<sourceBusID>
				canbus2
			</sourceBusID>
			<sourceObjectID>
				3
			</sourceObjectID>
			<sourceType>
				can
			</sourceType>
			<sourceChannel>
				
			</sourceChannel>
		</source>
		<destination>
			<destinationBusID>
				canbus2
			</destinationBusID>
			<destinationObjectID>
				3
			</destinationObjectID>
			<destinationType>
				can
			</destinationType>
			<destinationChannel>
				
			</destinationChannel>
			<backboneCTID>
				200
			</backboneCTID>
		</destination>
		<options>			
			<holdUpTime>
			
			</holdUpTime>
		</options>
	</item>
	
</routingTable>
